# 数据集根目录
path: ../datasets/fruit_dataset

# 训练、验证、测试集的相对路径
train: train/images
val: valid/images
test: test/images  # 如果解压后没有test文件夹，这行代码会自动忽略

# 类别数量
nc: 21

# 类别名称 (严格对应你的数据集)
names:
  0: apple
  1: avacado
  2: banana
  3: bell pepper
  4: cabbage
  5: carrot
  6: chili pepper
  7: coconut
  8: courgette
  9: cucumber
  10: eggplant
  11: kiwi
  12: lemon
  13: orange
  14: peach
  15: pear
  16: potato
  17: red cabbage
  18: tangerine
  19: tomato
  20: watermelon